/** Runs before `astro build` (npm prebuild hook) and `npm run dev`. */
import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compileFromFile } from "json-schema-to-typescript";
import { ModelLoadError, type Manifest } from "../src/data/load";
import { findModelDir } from "../src/data/modelDir";
import { ENTITY_TYPES } from "../src/data/pageTypes";
import { validateModelDir } from "../src/data/validate";

const webRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const generatedDir = path.join(webRoot, "src", "generated");

function pascalCase(type: string): string {
  return type
    .split("_")
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

async function generateTypes(modelDir: string): Promise<void> {
  await rm(generatedDir, { recursive: true, force: true });
  await mkdir(generatedDir, { recursive: true });
  for (const type of ENTITY_TYPES) {
    const source = await compileFromFile(path.join(modelDir, "schema", `${type}.schema.json`), {
      bannerComment: `// Generated from ${type}.schema.json by scripts/prebuild.ts. Do not edit.`,
      additionalProperties: false,
    });
    await writeFile(path.join(generatedDir, `${type}.ts`), source);
  }
  const reexports = ENTITY_TYPES.map((t) => `export type { ${pascalCase(t)} } from "./${t}";`).join("\n");
  const imports = ENTITY_TYPES.map((t) => `import type { ${pascalCase(t)} } from "./${t}";`).join("\n");
  const fields = ENTITY_TYPES.map((t) => `  ${t}: ${pascalCase(t)};`).join("\n");
  await writeFile(
    path.join(generatedDir, "index.ts"),
    `// Generated by scripts/prebuild.ts. Do not edit.\n${reexports}\n${imports}\n\nexport interface EntityTypeMap {\n${fields}\n}\n`,
  );
}

async function copyImages(modelDir: string, buildId: string): Promise<void> {
  const target = path.join(webRoot, "public", "images");
  const marker = path.join(target, ".build-id");
  const wanted = `${buildId}:${modelDir}`;
  const current = await readFile(marker, "utf-8").catch(() => "");
  if (current === wanted) {
    console.log("prebuild: images up to date");
    return;
  }
  await rm(target, { recursive: true, force: true });
  try {
    await cp(path.join(modelDir, "images"), target, { recursive: true });
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== "ENOENT") throw e;
  }
  await mkdir(target, { recursive: true });
  await writeFile(marker, wanted);
  console.log(`prebuild: images copied from ${modelDir}`);
}

async function writeBuildInfo(modelDir: string, manifest: Manifest): Promise<void> {
  const info = {
    buildId: manifest.build_id,
    generatedAt: manifest.generated_at,
    modelDir: modelDir.split(path.sep).join("/"),
    counts: manifest.counts,
  };
  await writeFile(
    path.join(generatedDir, "build-info.ts"),
    `// Generated by scripts/prebuild.ts. Do not edit.\nexport const buildInfo = ${JSON.stringify(info, null, 2)} as const;\n`,
  );
}

async function prebuild(): Promise<void> {
  const modelDir = await findModelDir(path.join(webRoot, "..", "model"));
  const manifest = await validateModelDir(modelDir);
  console.log(`prebuild: model ${manifest.build_id} at ${modelDir}`);
  await generateTypes(modelDir);
  await copyImages(modelDir, manifest.build_id);
  await writeBuildInfo(modelDir, manifest);
}

try {
  await prebuild();
} catch (e) {
  console.error(e instanceof ModelLoadError ? `prebuild failed: ${e.message}` : e);
  process.exit(1);
}
